### ISSUE TITLE
Slow state retrieval from Pulumi Cloud when secrets are used

### ISSUE THREAD

**Issue by fernandocarletti** [pulumi/pulumi#15293]
### What happened?

We noticed some considerable slowness (40+ seconds) when making previews and updates, exporting stacks with the --show-secrets, or anything that causes secrets to be decrypted, especially in bigger stacks (100+ resources) which appears to be caused by the secrets decryption process in Pulumi Cloud.

There's a noticeable hang when starting or finishing an update, which appears to me to be related to this issue.

### Example

I ran benchmarks comparing different state and secrets backends: `Pulumi Cloud`, `AWS S3` with `passphrase`, `AWS S3` and `hashivault`. These are the results I got:

![image](https://github.com/pulumi/pulumi/assets/416930/f3b1ad17-05aa-4d89-ac59-dd6638caf27c)

Note that when using Pulumi Cloud the state retrieval takes ~40s in average to be downloaded.

### Output of `pulumi about`

```
CLI          
Version      3.102.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v21.5.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/[REDACTED]
User           [REDACTED]
Organizations  [REDACTED], [REDACTED]
Token type     personal

Pulumi locates its logs in /var/folders/0j/gg8mxfyx199g0n2k3d2k8yxr0000gn/T/ by default
```

Contact me in the Slack Community if the username and organization are needed, please.

### Additional context

This discussion started in the Community Slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1702296641773089

Edit: I just tested it with the biggest stack we have over here (1.8k resources, 3.7k secrets) and it takes ~17min do fetch when `--with-secrets` is set and 4.6s when not set.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Very compelling numbers. This is unexpected and we'll take a look into it.

**Comment by fernandocarletti** [comment]
A bit more info. We moved our biggest stack to the Vault secret backend while keeping the state in Pulumi Cloud and we noticed the update time dropping 40% (~22min to ~14min) when adding two resources. There's a considerable hand with no output, the actual resources creation takes around 50s (~25s each). The rest there seems to be just Pulumi stuff.

**Comment by fernandocarletti** [comment]
I'm not sure if this info is useful or not, but here we go. When changing the secrets provider (`pulumi stack change secrets-provider hashivault://pulumi`) it was pretty fast, for the big-ass stack it took only 8 seconds. I even downloaded the state to make sure it was indeed updated, and it was. So the issue does not affect this case specifically, even though it changes every secret in the state (I'm not familiar with the way this process work, hence not sure if this info is useful or not).

**Comment by Frassle** [comment]
Hey all, I fixed an issue with `--show-secrets` doing more work than was actually needed, so it wasn't actually giving a good metric for decryption performance. It would be worth running your experiments again with the latest release. It might _still_ be much slower with the service secrets, but if it is we'll now know that's actually due to decryption costs.

**Comment by michele** [comment]
@Frassle I didn't try `pulumi stack export`, I just did `pulumi stack change secrets-provider gcpkms://uri` and `pulumi up` went from a good 5 minutes to show the preview to maybe 10 seconds, and from another 4-5 minutes to start applying the changes, to just a few seconds.

**Comment by fernandocarletti** [comment]
I re-run the tests just comparing with the vault since I believe the passphrase is irrelevant for the comparison, based on the earlier tests.

![image](https://github.com/pulumi/pulumi/assets/416930/1d88395c-6308-44c0-9e70-8c71e1197c0d)

The issue with the export seems fixed! 🎉 

Although for the update I still see a considerable difference when running `pulumi update --skip-preview`, where using the default secrets provider gives us 3x more execution time:
![image](https://github.com/pulumi/pulumi/assets/416930/71f634d7-6dc6-483e-ac3d-45656ef2b2a7)

**Comment by Frassle** [comment]
Well I'm happy the difference isn't so large anymore but that does look like there's still some scope for performance improvements here.
