### ISSUE TITLE
Panic on `up`

### ISSUE THREAD

**Issue by jeffijoe** [pulumi/pulumi#2738]
I can't say exactly how this came about, but what I do know is I was loosely following the Kubernetes The Prod Way guide.

I am using a `StackReference`, and as I was trying to make some of the outputs secret by wrapping in `pulumi.secret`, the next `up` caused Pulumi to say my GKE Cluster needed to be replaced, even though the outputs referenced in the template were not even changed, although one of them was from the referenced stack that had changed.

This is the panic:

```
Previewing update (worklayer-infrastructure-production):

     Type                             Name                                                          Plan       Info
     pulumi:pulumi:Stack              redacted
 -   ├─ gcp:container:Cluster         production                                                    delete     completing deletion from previous update
 >   └─ pulumi:pulumi:StackReference  worklayer-identity-production                                 read...
panic: runtime error: comparing uncomparable type resource.PropertyMap

goroutine 212 [running]:
github.com/pulumi/pulumi/pkg/resource.PropertyValue.DeepEquals(0x1dad140, 0xc000628e40, 0x1dad140, 0xc00104b6d0, 0x110)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/properties_diff.go:327 +0x2ee
github.com/pulumi/pulumi/pkg/resource.PropertyValue.Diff(0x1dad140, 0xc000628e40, 0x1dad140, 0xc00104b6d0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/properties_diff.go:242 +0x779
github.com/pulumi/pulumi/pkg/resource.PropertyMap.Diff(0xc00062b0b0, 0xc0010486f0, 0x0, 0x0, 0x0, 0x110)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/properties_diff.go:148 +0x297
github.com/pulumi/pulumi/pkg/resource.PropertyValue.Diff(0x1e7b500, 0xc00062b0b0, 0x1e7b500, 0xc0010486f0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/properties_diff.go:231 +0x65f
github.com/pulumi/pulumi/pkg/resource.PropertyMap.Diff(0xc00062b080, 0xc001049650, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/properties_diff.go:148 +0x297
github.com/pulumi/pulumi/pkg/engine.ShouldRecordReadStep(0x21aac80, 0xc000d0edb0, 0x4)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/engine/plan.go:329 +0x12a
github.com/pulumi/pulumi/pkg/engine.(*planActions).OnResourceStepPost(0xc000165950, 0x0, 0x0, 0x21aac80, 0xc000d0edb0, 0x0, 0x0, 0x0, 0x0, 0x402030203020302)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/engine/plan.go:303 +0x4fc
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeStep(0xc000846820, 0x4, 0x21aac80, 0xc000d0edb0, 0x0, 0xc000682240)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:296 +0x736
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeChain(0xc000846820, 0x4, 0xc000d00ce0, 0x1, 0x1)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:221 +0xe0
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker.func1(0xc000846820, 0x4, 0xc000d00ce0, 0x1, 0x1, 0xc000d306c0)
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:371 +0xc5
created by github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker
	/private/tmp/pulumi-20190514-48954-1vzsh32/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:368 +0x2c2
```

Before that panic, I got the following:

```
Previewing update (whatever-infrastructure-production):

     Type                             Name                                                          Plan        Info
     pulumi:pulumi:Stack              whatever-infrastructure-whatever-infrastructure-production
 >   ├─ pulumi:pulumi:StackReference  whatever-identity-production                                 read
 +-  ├─ gcp:container:Cluster         production                                                    replace     [diff: ~name,project]; 2 warnings
 ~   ├─ pulumi:providers:kubernetes   production                                                    update      [diff: ~kubeconfig]
 ~   ├─ kubernetes:apps:Deployment    hello-kubernetes                                              update      [diff: ~metadata]; 1 warning
 ~   └─ kubernetes:core:Service       hello-kubernetes                                              update      [diff: ~metadata]; 1 warning

Diagnostics:
  kubernetes:core:Service (hello-kubernetes):
    warning: The provider for this resource has inputs that are not known during preview.
    This preview may not correctly represent the changes that will be applied during an update.

  gcp:container:Cluster (production):
    warning: urn:pulumi:whatever-infrastructure-production::whatever-infrastructure::gcp:container/cluster:Cluster::production verification warning: "region": [DEPRECATED] Use location instead
    warning: urn:pulumi:whatever-infrastructure-production::whatever-infrastructure::gcp:container/cluster:Cluster::production verification warning: "region": [DEPRECATED] Use location instead

  kubernetes:apps:Deployment (hello-kubernetes):
    warning: The provider for this resource has inputs that are not known during preview.
    This preview may not correctly represent the changes that will be applied during an update.

Resources:
    ~ 3 to update
    +-1 to replace
    > 1 to read
    3 changes. 4 unchanged

Do you want to perform this update? yes
Updating (whatever-infrastructure-production):

     Type                             Name                                                          Status         Info
     pulumi:pulumi:Stack              whatever-infrastructure-whatever-infrastructure-production
 >   ├─ pulumi:pulumi:StackReference  whatever-identity-production                                 read
 +-  ├─ gcp:container:Cluster         production                                                    replaced       [diff: ~name,project]; 2 warnings
     └─ pulumi:providers:kubernetes   production                                                    **failed**     1 error

Diagnostics:
  pulumi:providers:kubernetes (production):
    error: pulumi:providers:kubernetes resource 'production's property 'kubeconfig' value {{{MY KUBECONFIG YAML IN ALL OF ITS GLORY}}} has a problem: provider property values must be strings

  gcp:container:Cluster (production):
    warning: urn:pulumi:whatever-infrastructure-production::whatever-infrastructure::gcp:container/cluster:Cluster::production verification warning: "region": [DEPRECATED] Use location instead
    warning: urn:pulumi:whatever-infrastructure-production::whatever-infrastructure::gcp:container/cluster:Cluster::production verification warning: "region": [DEPRECATED] Use location instead

Resources:
    +-1 replaced
    > 1 read
    2 changes. 4 unchanged

Duration: 2m52s
```

**Comment by lukehoban** [comment]
I believe this was fixed with https://github.com/pulumi/pulumi/pull/2737.  I expect a new release including this fix is imminent.  cc @ellismg

**Comment by jeffijoe** [comment]
I did it again. 😅 

It was when going between raw and `pulumi.secret`.

**Comment by jeffijoe** [comment]
Just want to add, I looked at the PR and saw the test case covered diffing 2 secrets, not a plain and a secret which I believe is what was happening.

**Comment by ellismg** [comment]
@jeffijoe Just to confirm, you are still seeing this even with `0.17.12` of Pulumi (you can install manually with `curl -L https://get.pulumi.com/ | bash -s -- --version 0.17.12`, it should be the default version soon)?

I augmented the test code to look like this locally:

```
func TestMismatchedPropertyValueDiff(t *testing.T) {
	t.Parallel()

	a1 := NewPropertyValue([]string{"a", "b", "c"})
	a2 := NewPropertyValue([]string{"a", "b", "c"})

	s1 := MakeSecret(a1)
	s2 := MakeSecret(a2)

	assert.True(t, s2.DeepEquals(s1))
	assert.True(t, s1.DeepEquals(s2))

	assert.False(t, a1.DeepEquals(s2))
	assert.False(t, a2.DeepEquals(s1))
}
```

And this test passes on `v0.17.12`

**Comment by jeffijoe** [comment]
@ellismg I installed via Brew, can I still do that?

**Comment by ellismg** [comment]
@jeffijoe 

> @ellismg I installed via Brew, can I still do that?

You can, but it may not be what you want.  If you run that script, it would install another copy of Pulumi into `~/.pulumi/bin` and then add some stuff to your bash profile to add that to the PATH.  You'd end up with two copies of Pulumi on your system, which may lead to confusion later.

I opened a PR to homebrew yesterday to update their version: https://github.com/Homebrew/homebrew-core/pull/39908, but it hasn't been merged yet.

You can also just download the tarball with the `pulumi` binary directly (https://get.pulumi.com/releases/sdk/pulumi-v0.17.12-darwin-x64.tar.gz) and extract that to a directory of your choosing, and temporarily add that to your `$PATH` to try it out, before HomeBrew is updated.

**Comment by jeffijoe** [comment]
Would replacing the brew version with the new binary work too? I’d rather not modify my bash profile 😄

**Comment by ellismg** [comment]
> Would replacing the brew version with the new binary work too? I’d rather not modify my bash profile smile

Yes, I believe that should work.

**Comment by jeffijoe** [comment]
Will try that tomorrow!

**Comment by ellismg** [comment]
> Will try that tomorrow!

Great!  With any luck, the official homebrew packages will also be updated soon enough.

**Comment by jeffijoe** [comment]
I downloaded the release from the link and am no longer getting a panic, however it still insists on replacing my K8S Cluster even though the only difference is I wrapped my master password in `pulumi.secret`. (this is a test cluster that I am going to take down so the secret in the photo isn't sensitive)

![image](https://user-images.githubusercontent.com/2505474/57909319-c7856300-7882-11e9-8bcd-856d54a9f520.png)

**Comment by jeffijoe** [comment]
And on the subject of diffing and equality checking (I assume that was the area of the code that caused the panic), it's also having trouble in the K8S provider:

![image](https://user-images.githubusercontent.com/2505474/57910757-53e55500-7886-11e9-8863-9e8abdc7cd54.png)

**Comment by lukehoban** [comment]
> It still insists on replacing my K8S Cluster even though the only difference is I wrapped my master password in pulumi.secret.

Was this something you saw during a preview, or also during the update itself?

**Comment by jeffijoe** [comment]
I saw it during preview and running `up` executed it.

**Comment by ellismg** [comment]
We solved the panic, so I think this is safe to close now.
