### ISSUE TITLE
Add tests for dependency tracking in nested `apply`s

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3282]
We appear to lose correct tracking of dependencies when an `Output` is returned from inside an `apply`.

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket1 = new aws.s3.Bucket("my-bucket");
const timeout = new Promise(res => setTimeout(res, 1000));
const bucket2 = new aws.s3.Bucket("my-bucket-2", {
    bucket: bucket1.bucket.apply(name => name +  "-and-another-one"),
});
export const bucketName = bucket2.bucket;

```

Deployed as above, the state file includes information about a dependency of bucket2 on bucket1.  

```json
                "dependencies": [
                    "urn:pulumi:dev::deptest::aws:s3/bucket:Bucket::my-bucket"
                ],
```

However, deployed as below, it does not include this dependency information in the state file.  The dependency is in practice observed during deployment, but this could lead to delete order issues, as well as potentially other delete before replace cascade issues.  

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket1 = new aws.s3.Bucket("my-bucket");
const timeout = new Promise(res => setTimeout(res, 1000));
const bucket2 = new aws.s3.Bucket("my-bucket-2", {
    bucket: pulumi.output(true).apply(() => {
        return bucket1.bucket.apply(name => name +  "-and-another-one");
    }),
});
export const bucketName = bucket2.bucket;
```

**Comment by CyrusNajmabadi** [comment]
This is documented explicitly in our API:

```ts
     * ```ts
     * var d1: Output<SomeVal>;
     * var d2 = d1.apply(v => v.x.y.OtherOutput); // getting an output off of 'v'.
     * ```
     *
     * In this example, taking a dependency on d2 means a resource will depend on all the resources
     * of d1.  It will *not* depend on the resources of v.x.y.OtherDep.
```

The primary reason this doesn't work is that 'dependent resources' are eagerly provided at Output construction time.   We could consider trying to make these asynchronously computed as well.  In that case, it might be possible to support this (though terrifying) :)

**Comment by lukehoban** [comment]
Got it. I assumed as much. But I do think this can lead to a really subtle hole in our dependency tracking. And I hit a real world use case where this was unavoidable in the transformations PR tests. 

It also seems we should be able to be correct here - we don’t actually use the dependency information until the output is fully resolved.

**Comment by CyrusNajmabadi** [comment]
Well, i just hit this myself.  Which makes me 10x more amenable to wanting to fix this as well :D  

It's definitely a subtle hole.  @pgavlin indicates he may already have a PR here.  Both he and I agree that this likely isn't too hard to actually fixup at the pulumi/pulumi levle.  One niggle is that we believe we may have downstream internal consumers (i.e. pulumi/eks) that might be poking into the internal `.resources` property.  So we'd have to be sure we weren't breaking anything there.

But, outside of that, this should be doable.

**Comment by pgavlin** [comment]
https://github.com/pulumi/pulumi/pull/2288 was intended to solve this.

**Comment by lukehoban** [comment]
We believe this is fixed now in Node.js.  Remaining work will be to port these changes to the other languages as well (along with tests).
- [x] Node.js
- [ ] Python
- [ ] .NET
- [ ] Go

**Comment by tricky42** [comment]
I am experiencing this problem using Node.js / Pulumi v2.13.0.

**Comment by joeduffy** [comment]
I tried to repro this in all four languages, and the dependency from `bucket2` on `bucket` was found in the resulting statefile in all four cases. Does that mean this is actually no longer a problem and that all that is required now is to write tests?

cc @lukehoban @pgavlin 

Test programs below:

### TypeScript

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket1 = new aws.s3.Bucket("my-bucket");
const bucket2 = new aws.s3.Bucket("my-bucket-2", {
    bucket: pulumi.output(true).apply(() => {
        return bucket1.bucket.apply(name => name +  "-and-another-one");
    }),
});
export const bucketName = bucket2.bucket;
```

### Python

```python
"""An AWS Python Pulumi program"""

import pulumi
from pulumi_aws import s3

bucket1 = s3.Bucket('my-bucket')
bucket2 = s3.Bucket('my-bucket-2',
    bucket = pulumi.Output.from_input(True).apply(
        lambda _: bucket1.bucket.apply(
            lambda name: name + '-and-another-one')))

pulumi.export('bucket_name', bucket2.id)
```

### C#

```csharp
using Pulumi;
using Pulumi.Aws.S3;

class MyStack : Stack
{
    public MyStack()
    {
        var bucket1 = new Bucket("my-bucket");
        var bucket2 = new Bucket("my-bucket-2", new BucketArgs {
            BucketName = Output.Create(true).Apply((_) =>
                bucket1.BucketName.Apply((name) => name + "-and-another-one"))
        });

        this.BucketName = bucket2.Id;
    }

    [Output]
    public Output<string> BucketName { get; set; }
}
```

### Go

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		bucket1, err := s3.NewBucket(ctx, "my-bucket", nil)
		if err != nil {
			return err
		}
		bucket2, err := s3.NewBucket(ctx, "my-bucket-2", &s3.BucketArgs{
			Bucket: pulumi.Bool(true).ToBoolOutput().ApplyT(func(_ bool) pulumi.StringOutput {
				return bucket1.Bucket.ApplyT(func(name string) string {
					return name + "-and-another-one"
				}).(pulumi.StringOutput)
			}).ApplyT(func(s interface{}) string {
				// hm, the result is an AnyOutput unless we have this extra ApplyT:
				return s.(string)
			}).(pulumi.StringOutput),
		})
		if err != nil {
			return err
		}

		ctx.Export("bucketName", bucket2.ID())
		return nil
	})
}
```

**Comment by lukehoban** [comment]
> Does that mean this is actually no longer a problem and that all that is required now is to write tests?

Yes - that appears to be the case, and is not too surprising to me given other changes we've made that touched these over the last year.  I reproduced all your examples above and confirmed that all four showed the expected dependency of `my-bucket-2` on `my-bucket`.

> `// hm, the result is an AnyOutput unless we have this extra ApplyT:`

This is tracked in https://github.com/pulumi/pulumi/issues/6073.

**Comment by tcarrio** [comment]
I believe I have come across a case that implicates this as a bug still. I can reproduce sometime this week, but due to a high level of flexibility in inputs, objects are recursively processed to allow a singular output that can be acted upon. Otherwise, there were cases where you had an object with nested properties being serialized when doing string templating which obviously provides an undesired output :smile: 

In this case, we have found that the nested resources simply aren't being processed. My repro will also isolate this, as the case where this is done is also nested within another `.all([...])` which takes in roughly 7 arguments, one of which was the deeply nested output.

However, it seems this case can still occur. It's causing our diff to incorrectly show many deleted resources. Due to the preferred developer workflow there isn't too much that can be done to allow full flexibility if it does have to do with the multiple level of nested outputs. Will follow up here further later :+1:
