### ISSUE TITLE
Unable to get full values of an output without doing pulumi up --skip-preview

### ISSUE THREAD

**Issue by axblum** [pulumi/pulumi#3596]
In creating a simple stack that is composed of two resources, For the example, below I am creating a fastly service(resource) and a fastly dictionary items(resource)using the python SDK. In order to link dictionary_items to a service, one must pass `Servicev1.dictionaries` into the the `service_dictionary_itemsv1` In order for the items to be associated with service. This seemed to work in versions of Pulumi prior to 1.6.0. As shown below in the following examples:
```
     Type                                      Name                               Plan       Info
 +   pulumi:pulumi:Stack                       Fastly-api-ab-testing  create
 +   ├─ fastly:index:Servicev1                 api-ab-testing         create
     └─ fastly:index:ServiceDictionaryItemsv1  tb_datacenter_routing                         1 error
Diagnostics:
  fastly:index:ServiceDictionaryItemsv1 (tb_datacenter_routing):
    error: fastly:index/serviceDictionaryItemsv1:ServiceDictionaryItemsv1 resource 'tb_datacenter_routing' has a problem: Missing required property 'dictionaryId' 
```
In 1.5.1 we see the following 
```
I1127 11:36:36.353167   31278 eventsink.go:60] top-level input property translated: dictionary_id -> dictionaryId
but on 1.6.0  it never translates dictionary_id -> dictionaryID
```

Please let me know if you need any additional info. 
Thanks!

**Comment by pgavlin** [comment]
Can you share the code snippet that creates the two resources?

**Comment by axblum** [comment]
Here is the snippet that creates the dictionary items

```
class ServiceDictItemsFactory(object):
    """
    Creates A Factory for Dictionary Items
    """
    @classmethod
    def create(cls, dictionary, service, service_config):
        """
        Creates A Factory for Dictionary Items
        :param dictionary: Edge Dictionary we will be operating on
        :param service: ServiceV1 Service to operate on
        :param service_config: Service config
        :return: ServiceDictionaryItemsv1
        """

        resource_opts = create_resource_opts(service_config, dictionary, service=service)
        dictionary_id = pulumi.Output.from_input(service.dictionaries).apply(lambda x: ServiceDictItemsFactory.get_dictionary_id(x, dictionary.get("name")))
        return ServiceDictionaryItemsv1(
            dictionary["name"],
            resource_opts,
            service_id=service.id,
            dictionary_id=dictionary_id,
            items=dictionary["items"]
        )

    @staticmethod
    def get_dictionary_id(dictionaries, dict_name):
        for i in dictionaries:
            if dict_name == i["name"]:
                print(i)
                return i.get("dictionary_id")
```

from __main__.py 
```
        service = ServiceFactory.create(service_config, pwd=stack)
        # Returns a service object
        for dictionary in service_config["dictionaries"]:
            if dictionary.get("items"):
                ServiceDictItemsFactory.create(dictionary, service, service_config)
```
The service Factory is very similar in style, but returns a service resource. Let me know if you need any additional info

**Comment by axblum** [comment]
@pgavlin any updates on this. It appears for a short period of time, I was able to work around this by asking for the output twice but it looks like in 1.7.1 we are back to not being able to get the dictionaryID
Here is the error thrown by pulumi when doing pulumi preview fastly:index/serviceDictionaryItemsv1:ServiceDictionaryItemsv1 resource 'tb_datacenter_routing' has a problem: Missing required property 'dictionaryId'

```
class ServiceDictItemsFactory(object):
    """
    Creates A Factory for Dictionary Items
    """

    @classmethod
    def create(cls, dictionary, service, service_config):
        """
        Creates A Factory for Dictionary Items
        :param dictionary: Edge Dictionary we will be operating on
        :param service: ServiceV1 Service to operate on
        :param service_config: Service config
        :return: ServiceDictionaryItemsv1
        """
        resource_opts = create_resource_opts(service_config, dictionary, service=service)
        # Dirty Ugly hack to get the dictionary ID
        tmp_dictionary_id = service.dictionaries.apply(
            lambda x: ServiceDictItemsFactory.get_dictionary_id(x, dictionary.get("name")))
        print(tmp_dictionary_id)
        dictionary_id = pulumi.Output.all(service.id, tmp_dictionary_id).apply(ServiceDictItemsFactory.tmp)
        return ServiceDictionaryItemsv1(
            dictionary["name"],
            resource_opts,
            dictionary_id=dictionary_id,
            service_id=service.id,
            items=dictionary["items"]
        )

    @staticmethod
    def tmp(lst):
        print(lst[1])
        return lst[1]

    @staticmethod
    def get_dictionary_id(dictionaries, dict_name):
        for i in dictionaries:
            if dict_name == i["name"]:
                print(i)
                return i.get("dictionary_id")
```

**Comment by lukehoban** [comment]
I'm unfortunately struggling to recreate a full working repro of this - the code above seems to be missing the definition of `ServiceFactory.create`, and there's quite a lot going on that doesn't appear related to the issue here which I'm having trouble detangling.

Can you provide a standalone repro of this by any chance?

**Comment by axblum** [comment]
Hi Everyone, 
Thanks for taking a look into this. I have created a repro of an Issue, but its not specifically this issue.  Because there were many things that changed under the hood. The provider was updated many times, and so was Pulumi.  After creating a sample repo in order to attempt reproduce https://github.com/axblum/pulumi-repro. I am starting to think this is an issue with the provider. 

In this example we have two resources ServiceV1 and ServiceDictionaryItemsv1. The way the Fastly API works is that you must create the Dictionary prior to adding items to it in another resource. 
The problem lies that the state file appears to be returning an empty string for the dictionary_id.  The empty dictionary_id also appears to be in the state file as well.  Here is an example of how it would be done in terraform as showing an example. https://www.terraform.io/docs/providers/fastly/r/service_dictionary_items_v1.html#example-usage

Its also worth noting that the same paradigm also applies to ACLs. 
Please let me know if you would like me to create a new issue against pulumi-fastly or continue to track the issue here.

**Comment by paulgeringer** [comment]
Hey all, I work with @axblum and have been running into this specific issue. [This repo](https://github.com/axblum/pulumi-repro) provides a very straightforward reproduction of the issue. 

After considerable digging into the internals of the python-pulumi code, this issue seems eerily similar to https://github.com/pulumi/pulumi-azure/issues/192. This ticket was ostensibly fixed with PR https://github.com/pulumi/pulumi/pull/3014, which was an attempt to resolve this overall bug ticket https://github.com/pulumi/pulumi/issues/2433. We have been using the current checkout of master from pulumi and are still hitting into this issue.

I haven't been able to conclusively find the exact cause of this issue from debugging the python code. As best as I can tell, this property is coming back as empty/unknown during a `preview` and an `up`, and is then dropped entirely when generating the overall state causing the resulting error. If any changes are made to the dictionaries after doing a `pulumi up --skip-preview`, including new entries, all dictionary_ids are dropped and the problem re-emerges.

By following suggestions in 192, I was able to generate https://github.com/axblum/pulumi-repro/pull/1. This allows us to get passed the preview step now, since it's hard-coding the dictionary_id property on the dictionary items, but an `up` will still fail since the dictionary doesn't actually exist yet.

My best guess right now is that the level of nesting for this specific field is preventing pulumi from recognizing it as a field to translate and retain.

Let me know if you need any additional steps on reproducing this issue.

**Comment by zhaitin-quotient** [comment]
Here is a very simple repro I've for a similar issue:
```
from pulumi_gcp import compute, dns

instance = compute.Instance(
    resource_name="test-instance",
    project="test-project",
    boot_disk={
        "initializeParams": {
            "size": 10,
        }
    },
    machine_type="f1-micro",
    network_interfaces=[{"network": "test", "subnetwork": "test"}],
    zone="us-east1-c",
)

dns.RecordSet(
    resource_name="test-dns",
    name="test.dns.com",
    managed_zone="test-zone",
    rrdatas=[instance.network_interfaces.apply(lambda n: n[0]["networkIp"])],
    ttl=60,
    type="A",
    project="test-project",
)
```

Pulumi update fails with:
```
error: Traceback (most recent call last):
      File "/home/zacharya/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 50, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 89, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      ...
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 325, in do_register
        resolver = await prepare_resource(res, ty, custom, props, opts)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 88, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 68, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 95, in serialize_property
        props.append(await serialize_property(elem, deps, input_transformer))
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 173, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 114, in get_value
        val = await self._future
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 176, in run
        transformed: Input[U] = func(value)
      File "./__main__.py", line 23, in <lambda>
        rrdatas=[instance.network_interfaces.apply(lambda n: n[0]["networkIp"])],
    KeyError: 'networkIp
```

If I'll comment out the DNS record, create the instance and then comment out the DNS - it works, but then if I change something on the instance resource, it will fail again.

**Comment by zhaitin-quotient** [comment]
Here is a very simple repro I've for a similar issue:
```
from pulumi_gcp import compute, dns

instance = compute.Instance(
    resource_name="test-instance",
    project="test-project",
    boot_disk={
        "initializeParams": {
            "size": 10,
        }
    },
    machine_type="f1-micro",
    network_interfaces=[{"network": "test", "subnetwork": "test"}],
    zone="us-east1-c",
)

dns.RecordSet(
    resource_name="test-dns",
    name="test.dns.com",
    managed_zone="test-zone",
    rrdatas=[instance.network_interfaces.apply(lambda n: n[0]["networkIp"])],
    ttl=60,
    type="A",
    project="test-project",
)
```

Pulumi update fails with:
```
error: Traceback (most recent call last):
      File "/home/zacharya/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 50, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 89, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      ...
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 325, in do_register
        resolver = await prepare_resource(res, ty, custom, props, opts)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 88, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 68, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 95, in serialize_property
        props.append(await serialize_property(elem, deps, input_transformer))
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 173, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 114, in get_value
        val = await self._future
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 176, in run
        transformed: Input[U] = func(value)
      File "./__main__.py", line 23, in <lambda>
        rrdatas=[instance.network_interfaces.apply(lambda n: n[0]["networkIp"])],
    KeyError: 'networkIp
```

If I'll comment out the DNS record, create the instance and then comment out the DNS - it works, but then if I change something on the instance resource, it will fail again.

**Comment by lukehoban** [comment]
I can no longer repro the case reported by @zhaitin-quotient and although I don't have a full repro of the case from @axblum I suspect it no longer repros either.  There have been a number of changes and fixes that might have addressed this in the last 6 months - though I am unsure the precise change that would have fixed the error reported above.

```
Previewing update (dev)

View Live: https://app.pulumi.com/lukehoban/gcppreview/dev/previews/092dbf04-728b-40a0-8b7d-39500e03f43f

     Type                     Name            Plan
 +   pulumi:pulumi:Stack      gcppreview-dev  create
 +   ├─ gcp:compute:Instance  test-instance   create
 +   └─ gcp:dns:RecordSet     test-dns        create

Resources:
    + 3 to create

Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/lukehoban/gcppreview/dev/updates/10

     Type                     Name            Status
 +   pulumi:pulumi:Stack      gcppreview-dev  created
 +   ├─ gcp:compute:Instance  test-instance   created
 +   └─ gcp:dns:RecordSet     test-dns        created

Resources:
    + 3 created

Duration: 37s
```

Closing this out for now.

**Comment by zhaitin-quotient** [comment]
Just checked it, the issue still exists in Pulumi 2.16.2, with the same repro I gave:
```
warning: Pulumi will not be able to print a statefile permalink using these credentials. Neither a GoogleAccessID or PrivateKey are available. Try using a GCP Service Account.
Previewing update (test):
     Type                     Name           Plan       Info
 +   pulumi:pulumi:Stack      test-test  create     3 errors
 +   └─ gcp:compute:Instance  test-instance  create     
 
Diagnostics:
  pulumi:pulumi:Stack (test-test):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/zacharya/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 378, in do_register
        resolver = await prepare_resource(res, ty, custom, props, opts)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 88, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 79, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 108, in serialize_property
        props.append(await serialize_property(elem, deps, input_transformer))
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 200, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 186, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/zacharya/.local/lib/python3.6/site-packages/pulumi/output.py", line 175, in run
        transformed: Input[U] = func(value)
      File "./__main__.py", line 20, in <lambda>
        rrdatas=[instance.network_interfaces.apply(lambda n: n[0]["networkIp"])],
    KeyError: 'networkIp'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

```

**Comment by lukehoban** [comment]
> the issue still exists in Pulumi 2.16.2

Which version of `pulumi_gcp` are you using?  I expect this was fixed with a recent release of that package.

**Comment by zhaitin-quotient** [comment]
> > the issue still exists in Pulumi 2.16.2
> 
> Which version of `pulumi_gcp` are you using? I expect this was fixed with a recent release of that package.

`pulumi-gcp==3.25.0`, just upgraded to `pulumi-gcp==4.6.0` and it's working :tada:
Thanks! This issue was really annoying...
