### ISSUE TITLE
Python output dicts aren't fully proxied

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4040]
I'm running into an issue where `dict`s aren't fully populated during previews and so I run into `KeyError`s during `pulumi up`. I'm not quite sure of the root cause here and it could very well be that the Pulumi Kubernetes library is doing the wrong thing in resolving values before they are known. Or it may be that our general output proxying should be somehow deeply proxying `dict`s?

For example, this program:

```python
import pulumi
import pulumi_kubernetes as k8s

# Create resources from standard Kubernetes guestbook YAML example.
def make_frontend_public(obj):
    if obj['kind'] == "Service" and obj['metadata']['name'] == "frontend":
        obj['spec']['type'] = "LoadBalancer"
guestbook = k8s.yaml.ConfigFile('guestbook', 'guestbook-all-in-one.yaml',
    transformations=[make_frontend_public])

# Export the private cluster IP address of the frontend.
frontend = guestbook.get_resource('v1/Service', 'frontend')
pulumi.export('private_ip', frontend.spec['cluster_ip'])
pulumi.export('public_ip', frontend.status['load_balancer']['ingress'][0]['ip'])
```

fails during preview with this error:

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 80, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 440, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 68, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 173, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/output.py", line 114, in get_value
        val = await self._future
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/output.py", line 155, in run
        value = await self._future
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/output.py", line 176, in run
        transformed: Input[U] = func(value)
      File "/Users/joeduffy/temp/k8s-yaml/venv/lib/python3.7/site-packages/pulumi/output.py", line 235, in <lambda>
        return self.apply(lambda v: UNKNOWN if isinstance(v, Unknown) else cast(Any, v)[key], True)
    KeyError: 'cluster_ip'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

If I run this with `pulumi up --skip-preview`, it works fine.

Notably, I get what I expect in the Node.js equivalent of this code:

```
import * as k8s from "@pulumi/kubernetes";

// Create resources from standard Kubernetes guestbook YAML example.
const guestbook = new k8s.yaml.ConfigFile("guestbook", {
    file: "guestbook-all-in-one.yaml",
    transformations: [(obj: any) => {
        if (obj.kind === "Service" && obj.metadata.name === "frontend") {
            obj.spec.type = "LoadBalancer";
        }
    }],
});

// Export the private cluster IP address of the frontend.
const frontend = guestbook.getResource("v1/Service", "frontend");
export const privateIp = frontend.spec.clusterIP;
export const publicIp = frontend.status.loadBalancer.ingress[0].ip;
```

One other difference between Python that I'll mention, as I assume it's related, is that exporting the `publicIp` fails for Python without the `transformations`, whereas it succeeds and simply exports `undefined` in the Node.js case. That's a fairly annoying situation because it means the Python code needs to conditionally export the value based on whether the service is of type `LoadBalancer`. This may be further evidence that the Kubernetes library is the culprit here?

**Comment by lukehoban** [comment]
This is basically due to https://github.com/pulumi/pulumi-azure/issues/192, which is a fairly deep issue with how we propagate unknowns during preview.  If there is a nested structure that is partially defined as input data, but more of it becomes populated as output data, we pass the partially populated data through during preview - treating it as "provided as input" - even though some fields that will be read as output are unpopulated - and often violating the typing of those fields.  

The difference between Node.js and Python here is due to `x["foo"]` returning `undefined` in Node.js if `"foo"` is not present, but returning a `KeyError` in Python under the same conditions.  That's just a language-specific design of property access in JavaScript vs. dict access in Python.  Were it not for the issue in the previous paragraph - this wouldn't really be a "problem" - but due to that issue, data which doesn't match the shape that is expected by reasonable user code is getting passed in.

We need to look more deeply into  https://github.com/pulumi/pulumi-azure/issues/192, and the overall design space around how data flows during preview.  We made three large overhauls here in the last 6 months, and each ended up with non-trivial downsides.  This issue is the downside of the most recent change which has been in place since https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#160-2019-11-20.

**Comment by joeduffy** [comment]
Since we can't know for sure whether a missing key truly would lead to a `KeyError`, or not, during a preview, I suppose we could return a sort of "tombstoned" output-style proxy map that just lies and returns empty proxies no matter what keys you try to get out of it?

**Comment by joeduffy** [comment]
In fact, isn't that actually what Node.js is doing? Not truly returning an `undefined`, since I can keep dotting into it without getting any errors?

**Comment by lukehoban** [comment]
Sort of - Node.js treats `a.b` as `a?.b`.  But that's not quite the issue here.  It's not that `a` is undefined.  It's that `.b` doesn't exist.  We could treat Python dict lookup as `a.get("b", {})` or something like that, but I feel like that starts to diverge very significantly from Python semantics.

The real problem is https://github.com/pulumi/pulumi-azure/issues/192.

**Comment by joeduffy** [comment]
I guess, for my specific scenario, I'm not following entirely why there has to be a behavioral difference here. Sorry for being slow -- as I'm not following the Azure example entirely either (the discussion seems to touch on a lot of different things -- the closest similar explanation I can find is [this](https://github.com/pulumi/pulumi-azure/issues/192#issuecomment-540072521)).

In my TypeScript, I can write this:

```typescript
frontend.spec.apply(v => console.log(`SPEC: ${JSON.stringify(v)}`));
frontend.status.apply(v => console.log(`STATUS: ${JSON.stringify(v)}`));
export const privateIp = frontend.spec.clusterIP;
export const publicIp = frontend.status.loadBalancer.ingress[0].ip;
```

During preview, I see the following:

```
Diagnostics:
  pulumi:pulumi:Stack (k8s-aio-dev):
    SPEC: {"ports":[{"port":80}],"selector":{"app":"guestbook","tier":"frontend"}}

Outputs:
  + publicIp: output<string>
```

As expected, status is empty. If I go ahead and perform the update, I see the following:

```
Diagnostics:
  pulumi:pulumi:Stack (k8s-aio-dev):
    SPEC: {"clusterIP":"10.51.253.161","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"guestbook","tier":"frontend"},"sessionAffinity":"None","type":"ClusterIP"}
    STATUS: {"loadBalancer":{}}

Outputs:
  + privateIp: "10.51.253.161"
```

Notably, also notice that the `publicIp` export is fine -- it just evaluates to `undefined` so it doesn't get exported, rather than it crashing.

_The same thing does not happen in Python, however._ Shouldn't it behave the same? In both cases, I'm using proxies instead of `apply`, which I would expect to behave similarly?

Notably:

```python
frontend.spec.apply(lambda v: print(f"SPEC: {v}"))
frontend.status.apply(lambda v: print(f"STATUS: {v}"))
pulumi.export('private_ip', frontend.spec['cluster_ip'])
pulumi.export('public_ip', frontend.status['load_balancer']['ingress'][0]['ip'])
```

During preview, this prints what I would expect:

```
Diagnostics:
  pulumi:pulumi:Stack (k8s-aio-py-dev):
    SPEC: {'ports': [{'port': 80.0}], 'selector': {'tier': 'frontend', 'app': 'guestbook'}}
```

But then fails due to the missing `cluster_ip` in the spec:

```
  error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
...
        return self.apply(lambda v: UNKNOWN if isinstance(v, Unknown) else cast(Any, v)[key], True)
    KeyError: 'cluster_ip'
```

If I skip the preview, it deploys and the `privateIp` export finally resolves as expected -- but then the `publicIp` export fails because the type is not `LoadBalancer`.

```
Diagnostics:
  pulumi:pulumi:Stack (k8s-aio-py-dev):
    STATUS: {'load_balancer': {}}
    SPEC: {'session_affinity': 'None', 'cluster_ip': '10.51.252.120', 'type': 'ClusterIP', 'ports': [{'target_port': 80.0, 'port': 80.0, 'protocol': 'TCP'}], 'selector': {'tier': 'frontend', 'app': 'guestbook'}}

   error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
  ...
       return self.apply(lambda v: UNKNOWN if isinstance(v, Unknown) else cast(Any, v)[key], True)
    KeyError: 'ingress'
```

Isn't the equivalent in Node.js -- and why it works -- that we fake up a proxy object that will intercept key lookups and continue returning proxies?

**Comment by lukehoban** [comment]
Just to note for anyone else who hits this, a workaround is to use `dict.get(key, default)` inside an `apply`.  So specifically replace this:

```py
pulumi.export('private_ip', frontend.spec['cluster_ip'])
```

with this:

```py
pulumi.export('private_ip', frontend.spec.apply(lambda spec: spec.get('cluster_ip', 'unknown')))
```

This ensures that if a `spec` is present that does not have a `cluster_ip`, an error will not be raised (and a dummy value `unknown`) will be used.  This will only happen during preview.

**Comment by lukehoban** [comment]
> Isn't the equivalent in Node.js -- and why it works -- that we fake up a proxy object that will intercept key lookups and continue returning proxies?

We do do that in both languages.  But that's not what's at "fault" here.  This actually has nothing to do with `Output`.  The actual raw dict value passed in for `frontend.spec` ultimately looks like `{ "type": "LoadBalancer" }` during an initial preview (because that's what your code provided as inputs).  And that dict does not have a `cluster_ip`.  So when you do `spec["cluster_ip"]` in Python, it is a KeyError.  When you do `spec["clusterIp"]` in Node.js, it is undefined, which then makes the equivalent code just silently "work".

**Comment by joeduffy** [comment]
Another repro, fwiw:

```
import pulumi
from pulumi_gcp import compute

# Declare shared disk / NIC settings.
boot_disk = compute.InstanceBootDiskArgs(
    initialize_params=compute.InstanceBootDiskInitializeParamsArgs(
        image='debian-cloud/debian-9'
    )
)
nic = compute.InstanceNetworkInterfaceArgs(
    network='default'
)

# Spin up the VMs.
i1 = compute.Instance('instance1',
    machine_type='e2-medium',
    boot_disk=boot_disk,
    network_interfaces=[nic]
)

i2 = compute.Instance('instance2',
    machine_type='e2-medium',
    boot_disk=boot_disk,
    network_interfaces=[nic]
)

# Export the IP addresses.
both_ip_addresses = pulumi.Output.all(
    i1.network_interfaces[0].network_ip,
    i2.network_interfaces[0].network_ip
).apply(lambda both: [both[0], both[1]])
pulumi.export('ip_addresses', both_ip_addresses)
```

**Comment by lukehoban** [comment]
The core issue here remains https://github.com/pulumi/pulumi-azure/issues/192.  It's not clear to me yet what else we could hope to do here to improve things.  Plausibly we could lift/proxy a `get` method onto outputs that wrap dicts?

**Comment by joeduffy** [comment]
I'll admit, I've never truly understood what #192 has to do with this, but it may be just because that bug's history is difficult for me to track down since it's been closed and reopened with numerous repos over time.

I put together a quick hack of what I'd always imagined the fix to this to look like: https://github.com/pulumi/pulumi/commit/458d7a22495fb24625e2fc60414f722db027e5de. I'm sure there are reasons that won't work but at least for my GCP repo above, it does the expected thing.

**Comment by lukehoban** [comment]
> I've never truly understood what pulumi/pulumi-azure#192 has to do with this, especially as that's a bug in the Azure repo and this seems like a much more widespread issue, but it may be just because that bug's history is difficult for me to track down since it's been closed and reopened with numerous repros over time.

That issue is not Azure specific - and we should at this point open a new issue with more clarity - but the bug that tracks is the root of why "undefined" values get returned into `apply`s during previews (instead of skipping invoking the `apply`s) when they ideally should not.  If this were fixed, the code above would know immediately that `both_ip_addresses` was unknown without any changes.

The fix in https://github.com/pulumi/pulumi/commit/458d7a22495fb24625e2fc60414f722db027e5de looks interesting!  I'll need to take a deeper look at this - and would love @justinvp and @komalali's thoughts.  This is essentially a realization of the "Plausibly we could lift/proxy a get method onto outputs that wrap dicts?" idea I noted above.  This is notably *not* what we do in TypeScript - but could plausibly be a solution for the way this issue manifests in Python?  It does feel strange to try to change the meaning of `[]` and `.` in Python during previews when operating on known values though...

**Comment by joeduffy** [comment]
>  It does feel strange to try to change the meaning of [] and . in Python during previews when operating on known values though...

They aren't known values, though. Apparently certain entries get added to them post-apply. Is there any way to know what properties are missing in advance? If yes, a better solution might be to eagerly populate those entries with UNKNOWNs.

**Comment by lukehoban** [comment]
>  Is there any way to know what properties are missing in advance?

This is what https://github.com/pulumi/pulumi-azure/issues/192 is all about.  The whole enclosing `Output` here should be UNKNOWN if any constituent pieces of it are, which would avoid these `apply` callbacks (the implicitly lifted ones in this case) from running, which would avoid having to deal with this.  If we decide we cannot or will not fix https://github.com/pulumi/pulumi-azure/issues/192, then we will be in a situation where there will in some cases be `undefined` values floating around inside values passed into `apply`s (including where `undefined` is not even type-wise legal!) that users will have to deal with.  These will act like "known" values from the perspective of `Output`/`apply` semantics, but with invalid/undefined values in them.  To a meaningful extent, this would degrade the whole point of `Output` and `apply`, which is that they avoid making users deal with writing branching code to deal with both the known and unknown cases.

If we can't or won't fix https://github.com/pulumi/pulumi-azure/issues/192, then indeed we'll need to find way to mitigate this problem elsewhere, like https://github.com/pulumi/pulumi/commit/458d7a22495fb24625e2fc60414f722db027e5de.  But (a) that kind of solution will only work for Python and possibly Node.js (b) it seems pretty clear it can't address this fully generally - you will still observe these `undefined` (*not* UNKNOWN) values in some case.

>  If yes, a better solution might be to eagerly populate those entries with UNKNOWNs.

I'm not sure whether @pgavlin has looked into this approach to https://github.com/pulumi/pulumi-azure/issues/192.  Curious his thoughts here as well.

**Comment by joeduffy** [comment]
Can we create an issue in pulumi/pulumi that describes the problem succinctly? I honestly can't follow what's going on in pulumi/pulumi-azure#192. The issue described is something specific to Azure and then the bug's history is essentially "it's fixed", "nope it's not fixed", "here's another repro" -- if there's a core pulumi/pulumi bug, we should track it as such with a clear description of the underlying problem. I _think_ you're saying the problem is that we shouldn't consider maps to be known because they can always have different elements during the final resolution, but I don't understand if that's _all_ maps, _some_ maps, or whether we know enough to get more precise/fine-grained. I also don't understand the comparisons with Node.js -- I have encountered this problem in Python many times now (as have customers) and I don't believe we've ever seen anybody hit something like this in Node.js, and yet I understand that yes Node.js has maps so I don't quite understand why we don't get bitten (maybe it's just because we just don't use maps for resource properties?) -- but in any case, it would be good to cover the language-specific nuances in the issue description also. This issue seems like a fairly serious bug deep in the core of the Python runtime, has been open quite a long time, and I would like to ask that we prioritize getting to a fix soon on this one.

**Comment by lukehoban** [comment]
Two changes have improved the situation here significantly:
1. We have fixed https://github.com/pulumi/pulumi-azure/issues/192 via https://github.com/pulumi/pulumi-terraform-bridge/pull/308.
2. The Python SDK now offers, and promotes, use of properties instead of dicts for accessing outputs

Due to (1), the repro in https://github.com/pulumi/pulumi/issues/4040#issuecomment-729173869 no longer hits an error.

Due to (2), this variant (which is what we would encourage as idiomatic Python code in all examples now) of the repro in https://github.com/pulumi/pulumi/issues/4040#issue-577552256 no longer hits an error:

```py
import pulumi
import pulumi_kubernetes as k8s

# Create resources from standard Kubernetes guestbook YAML example.
def make_frontend_public(obj):
    if obj['kind'] == "Service" and obj['metadata']['name'] == "frontend":
        obj['spec']['type'] = "NodePort"
guestbook = k8s.yaml.ConfigFile('guestbook', 'guestbook-all-in-one.yaml',
    transformations=[make_frontend_public])

# Export the private cluster IP address of the frontend.
frontend = guestbook.get_resource('v1/Service', 'frontend')
pulumi.export('private_ip', frontend.spec.cluster_ip) # Note that this uses properties instead of dict lookups
pulumi.export('public_ip', frontend.status.load_balancer.ingress[0].ip)
```

However, the original repro does still trigger the original error.  There's a lot going on in that example that isn't critical to this issue though - so here's a smaller example that triggers the same error for the same reason:

```py
service = k8s.core.v1.Service("frontend", 
    metadata={
        "name": "frontend"
    },
    spec={
        "type": "NodePort",
        "ports": [{"port": 80}],
        "selector": { "app": "guestbook", "tier": "frontend" },
    }
)

pulumi.export('private_ip', service.spec.apply(lambda spec: spec["cluster_ip"]))
```

A few things to note about this:
1. It can be fixed by replacing `spec["cluster_ip"]` with `spec.get("cluster_ip")` or `spec.cluster_ip` (both of these return `None` instead of throwing).
2. It can be written more simply as `service.spec.cluster_ip` which also works.
3. It cannot be written more simply as `service.spec["cluster_ip"]` (because that is ultimately the same as the case that errors above) or `service.spec.get("cluster_ip")` (because we don't "lift" a `.get` onto `Output[dict]`).
4. When written as `service.spec.apply(lambda spec: spec.get("cluster_ip"))` which works, this behaves the same as the TypeScript equivalent `service.spec.apply(spec => spec["cluster_ip"])` (and doesn't error).  Despite the similarity to the Python form `service.spec.apply(lambda spec: spec["cluster_ip"])`, the latter errors because dict lookup throws on invalid keys in Python.
5. The change in https://github.com/pulumi/pulumi/commit/458d7a22495fb24625e2fc60414f722db027e5de wouldn't prevent the error in this code, though it would prevent the error in the `service.spec["cluster_ip"]` case (by making it not mean the same thing as `service.spec.apply(lambda spec: spec["cluster_ip"])`.

With the most common causes of this now fixed (at least in idiomatic usage), there are two things we could still do to address the remaining potential cases that might hit issues here:
1. Lift a `get` method onto `Output[dict]` so that the one major inconsistency above can be handled - that is that users could choose to write a working version of this as `service.spec.get("cluster_ip")`.
2. Take a change like https://github.com/pulumi/pulumi/commit/458d7a22495fb24625e2fc60414f722db027e5de to allow `service.spec["cluster_ip"]` to also work, even though `service.spec.apply(lambda spec: spec["cluster_ip"])` still would not (increasing inconsistency, but pragmatically addressing an additional case that users might hit).

**Comment by logileifs** [comment]
I'm hitting this same annoying bug and I'm not really sure how to get around it.  
I've been following the advice in this issue as much as possible but this is still an issue in my case.  
I have actually found a workaround which is just so obscure that it's not really acceptable to me.  

(1) This works:
```python
from pulumi_kubernetes.core import v1 as core
from pulumi_kubernetes.helm import v3 as helm

ingress_ns_name = 'ingress'
ingress_ns = core.Namespace(
	'ingress-namespace',
	metadata={'name': ingress_ns_name},
	opts=pulumi.ResourceOptions(
		parent=cluster,
		depends_on=[cluster],
		provider=k8s_provider,
	)
)

ingress_contour = helm.Chart(
	'contour',
	helm.ChartOpts(
		namespace=ingress_ns.metadata.name,
		chart='contour',
		version="15.0.1",
		values={},
		transformations=[],
		fetch_opts=helm.FetchOpts(
			repo='https://charts.bitnami.com/bitnami'
		)
	),
	opts=pulumi.ResourceOptions(
		parent=ingress_ns,
		provider=k8s_provider,
		depends_on=[ingress_ns],
		custom_timeouts=pulumi.CustomTimeouts(
			create="30m",
			delete="30m"
		)
	)
)
svc = ingress_contour.get_resource('v1/Service', "ingress/contour-envoy")
ingress_ip = svc.status.apply(lambda s: s.load_balancer.ingress[0].ip)
```

(2) This does not:
```python
from pulumi_kubernetes.core import v1 as core
from pulumi_kubernetes.helm import v3 as helm

ingress_ns_name = 'ingress'
ingress_ns = core.Namespace(
	'ingress-namespace',
	metadata={'name': ingress_ns_name},
	opts=pulumi.ResourceOptions(
		parent=cluster,
		depends_on=[cluster],
		provider=k8s_provider,
	)
)

ingress_contour = helm.Chart(
	'contour',
	helm.ChartOpts(
		namespace=ingress_ns_name,
		chart='contour',
		version="15.0.1",
		values={},
		transformations=[],
		fetch_opts=helm.FetchOpts(
			repo='https://charts.bitnami.com/bitnami'
		)
	),
	opts=pulumi.ResourceOptions(
		parent=ingress_ns,
		provider=k8s_provider,
		depends_on=[ingress_ns],
		custom_timeouts=pulumi.CustomTimeouts(
			create="30m",
			delete="30m"
		)
	)
)
svc = ingress_contour.get_resource('v1/Service', "ingress/contour-envoy")
ingress_ip = svc.status.apply(lambda s: s.load_balancer.ingress[0].ip)
```
And I get this weird error:
```
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/logileifs/infra/dev/previews/e5cd6199-4b50-492b-9afb-c44dc3c74849

     Type                 Name       Plan     Info
     pulumi:pulumi:Stack  infra-dev           1 error

Diagnostics:
  pulumi:pulumi:Stack (infra-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/logi/.pulumi/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 137, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 83, in wait_for_rpcs
        raise exn from cause
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 872, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 176, in prepare_resource
        serialized_props = await rpc.serialize_properties(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 213, in serialize_properties
        result = await serialize_property(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 466, in serialize_property
        value = await serialize_property(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 449, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/output.py", line 129, in get_value
        val = await self._future
              ^^^^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/output.py", line 175, in run
        value = await self._future
                ^^^^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/output.py", line 175, in run
        value = await self._future
                ^^^^^^^^^^^^^^^^^^
      File "/home/logi/.virtualenvs/skelfir-infra/lib/python3.11/site-packages/pulumi/output.py", line 175, in run
        value = await self._future
                ^^^^^^^^^^^^^^^^^^
      [Previous line repeated 1 more time]
    AttributeError: 'set' object has no attribute '__dict__'
```

For some reason in (1) when the namespace is set to `ingress_ns.metadata.name` everything works as expected but when I set the namespace to the string value (2) I can no longer run `pulumi preview`.  
So in order to be able to run `pulumi preview` future me and any other developer who touches on the project has to remember to not change how the namespace is set.  
Is there really no fix for this or no better workaround?  
I need to retrieve the IP address that gets allocated to the envoy service so I can update some DNS records, is there perhaps any better way to do that using pulumi?  
I'm using DigitalOcean Kubernetes by the way

**Comment by aureq** [comment]
@logileifs A possible explanation to the difference in behavior is that when you use `ingress_ns.metadata.name` (which is an Output), the value is not yet know. This tells the Pulumi engines that some information aren't yeet available and need to be resolved when appropriate (ie, not during preview). If the value is know (a string), then the engine assumes all the information is present, including the resource itself.
