### ISSUE TITLE
Support for Solution file in .NET Core

### ISSUE THREAD

**Issue by Rookian** [pulumi/pulumi#4185]
I have one csproj file within one Visual Studio solution. 

When I run `pulumi up` I get the following error:

>  MSBUILD : error MSB1050: Specify which project or solution file to use because the folder "." contains more than one project or solution file.

Please make it possible to explicitly pass in the correct csproj file via pulumi console or pulumi stack configuration or determine the csproj file automatically and pass it to msbuild.

**Comment by mikhailshilkov** [comment]
This should work if you add a `main` entry to your `Pulumi.yaml` file, e.g.

```yaml
name: azure-cs
runtime: dotnet
main: Infra.csproj
description: A minimal Azure C# Pulumi program
```

**Comment by Rookian** [comment]
I think for C# projects the main entry should be set by pulumi automatically to ensure a better user experience. A lot of C# folks use Visual Studio, which has the nasty habit to create a solution file. After that you can't use pulumi anymore, because msbuild does not know what to build.
What do you think?

**Comment by mikhailshilkov** [comment]
I expect most people would use our CLI to bootstrap a new project, and it doesn't create a `sln` file.

Out of curiosity, what was your flow when you ended up with both `sln` and `csproj` files in the same folder? To be clear, I'm not saying that's a wrong thing to do -- just want to understand the scenario better.

**Comment by Rookian** [comment]
When you open the csproj file in Visual Studio 2019 after you initialized pulumi and you want to save everything or you like to leave Visual Studio 2019, it wants to create a corresponding solution file. I tried to find a way to prevent Visual Studio from creating solution files, but could not find anything so far. 

It also might be that people still want to have one solution where they work with a pulumi project and one project for deploying things like websites or doing other stuff.

I think pulumi should distinguish between VS Code and VS 2019 users:
- For VS Code: Leave it as it is
- For VS 2019: Create a solution, create a separate folder for csproj, fill the main entry, put Pulumi.yaml at solution level.

**Comment by mikhailshilkov** [comment]
Got you, thanks for the feedback @Rookian!

Possible improvements that make the most sense to me here:
- Catch the `MSBUILD` error above and give a more helpful error message suggesting further options (`main` option, or moving the `sln` file out of the folder)
- Add the `main` option to our .NET templates
- Add some heuristics into our CLI, e.g. list all `sln` and `xxproj` files in CWD, if there are more than one - pick the only `xxproj` file or give the descriptive error above

@lukehoban @leezen Would appreciate your opinion regarding these options and how they fit with other languages (including potential new runtimes).

**Comment by leezen** [comment]
I think there are two aspects to this: what the model is today and what we want the model to be in the future.

Today, the model is very much built around the entry point as a 'script' (see also: https://github.com/pulumi/pulumi/issues/1641#issuecomment-574453997). To me, doing things like the improvements mentioned above fit into that model.

Separately, there's a question of do we want a different model in the future? I can imagine scenarios where the entry point is more user-defined and more build-driven, e.g. in Typescript today, we run `ts-node` which makes it harder for someone who wants to manage their own build (e.g. use gulp or whatever else).

The last of the above options seems potentially fragile to me and would be better addressed by thinking about what the future model might look like, what use cases exist, and how to address those in a more holistic way. So I would be in favor of doing the first two, but not the last one.

**Comment by mikhailshilkov** [comment]
Agreed about the new model.

I don't feel great about filling `main` by default. I suspect people would often rename their projects and then hit a mismatch vs. the auto-configured `yaml` file.

I'll start with a good error message.

**Comment by TechWatching** [comment]
What is the status of this issue? Still a problem for me today.

**Comment by jetersen** [comment]
This is a problem if you want developer teams to own their IAM / Other Cloud resources bits their application needs, and you ask them to add a Pulumi csproj to their existing solution. 😅
